### ISSUE TITLE
$client->getActiveOrders() returns volume as an INT (no decimal)

### ISSUE THREAD

**Issue by muffettsman** [hitbtc-com/hitbtc-php-sdk#2]
/api/1/trading/orders/active return seems to strip the decimal out of quantity in this example i have a sell order for 200 (in the gui it reads as 200.000).

SNC 0 reserved:200 total 200
getactiveOrders:
object(Hitbtc\Model\Order)#144 (10) {
  ["orderId":protected]=>
  string(10) "asdf"
  ["clientOrderId":protected]=>
  string(32) "asdf"
  ["orderStatus":protected]=>
  string(3) "new"
  ["price":protected]=>
  string(8) "0.000014"
  ["quantity":protected]=>
  int(200000)
  ["type":protected]=>
  string(5) "limit"
  ["timeInForce":protected]=>
  string(3) "GTC"
  ["symbol":protected]=>
  string(6) "SNCBTC"
  ["side":protected]=>
  string(4) "sell"
  ["cumQuantity":protected]=>
  int(0)
}

**Comment by hitbtc-com** [comment]
api v1 uses lots as quantity. Please read doc, or use api v2
