### ISSUE TITLE
How to use it, always shows class not found error

### ISSUE THREAD

**Issue by 200890234** [hitbtc-com/hitbtc-php-sdk#5]
Any files need to require where to call the classes? 
I tried to require class files according to the error, then another class not found error occurs. So many classes could not be found, I don't think it's the right way to do like this. Can anyone tell me how to use? 
I created a folder named Hitbtc under my project, after install the sdk through composer, therer are three items in the folder: vendor(directory), composer.json, composer.lock. Shall i change the default files position under the vendor directory?

my code used to be like this(don't know if i need to require files):
// require_once("Hitbtc/vendor/hitbtc-com/hitbtc-php-sdk/src/Hitbtc/PublicClient.php");
	// require_once("Hitbtc/vendor/hitbtc-com/hitbtc-php-sdk/src/Hitbtc/ProtectedClient.php");
	/*require_once("Hitbtc/vendor/guzzlehttp/guzzle/src/Client.php");
	require_once("Hitbtc/vendor/guzzlehttp/guzzle/src/functions.php");*/
	// require_once("Hitbtc/vendor/guzzlehttp/guzzle/src/ClientInterface.php");
	// use GuzzleHttp\Client\PublicClient;
	// use GuzzleHttp\ClientInterface;
	$hitpub = new \Hitbtc\PublicClient($demo = false);
	$hitsec = new \Hitbtc\ProtectedClient(HITBTC_KEY, HITBTC_SECRET, $demo = false); //
	function getHitdepth($market,$coin,$limit){
		global $hitpub;
		$symbol=$coin.$market;
		$depth=$hitpub->getOderBook($symbol,$limit); // i tried to modify some functions to fit in v2 version of api
		return $depth;
	}

**Comment by hitbtc-com** [comment]
You should install it via composer
